/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package klaytn.openapi

import io.kotest.core.config.AbstractProjectConfig
import io.kotest.core.config.LogLevel
import io.kotest.core.spec.style.BehaviorSpec
import io.kotest.matchers.shouldBe

class KlaytnTypescriptAxiosClientCodeGenTest : BehaviorSpec({
    Given("Klaytn typescript axios code generator") {
        When("Model file name set to KlaytnModel") {
            Then("return 'klaytn-model as kebab case") {
                val codeGen = KlaytnTypescriptAxiosClientCodeGen()
                codeGen.toModelFilename("KlaytnModel").shouldBe("klaytn-model")
            }
        }
    }
})

object KotestProjectConfig : AbstractProjectConfig() {
    override var displayFullTestPath: Boolean? = true
}
